name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: git-checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install and Build
      run: |
        npm install
        npm run build
        
      
    - name: Build the Docker image using Dockerfile.dev
      run: docker build . --file Dockerfile.dev --tag sla686/react-portfolio:dev
    
    - name: Build the Docker image using Dockerfile.prod
      run: docker build . --file Dockerfile.prod --tag sla686/react-portfolio
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: public
    
#    - name: Login to DockerHub Registry
#      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      

      
#    - name: Push the tagged Docker image (dev)
#      run: docker push sla686/react-portfolio:dev
      
      
#    - name: Push the tagged Docker image (latest)
#      run: docker push sla686/react-portfolio:latest

  docker:
    runs-on: ubuntu-latest
    name: Deploy to Docker Hub
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push (development)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sla686/react-portfolio:dev
        
      - name: Build and push (production)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sla686/react-portfolio:latest
        



